name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - qa
      - main

permissions:
  id-token: write   # Required for OIDC authentication
  contents: read    # Default permission for accessing the repo

jobs:
  deploy-backend:
    name: Deploy Backend
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set auth
        id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          # value must come from the audience fiele in the service account key file #
          workload_identity_provider: "projects/571690378641/locations/global/workloadIdentityPools/github-wif-pool/providers/github-provider-id"
          # value is the email address of the service account #
          service_account: "github-wif-sa@iaac-gcp-data-mgt.iam.gserviceaccount.com"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
  
      - name: Check if GCS bucket exists
        id: check-bucket
        run: |
          if gsutil ls -b gs://iaac-gcp-data-mgt-terraform; then
              echo "Bucket already exists."
              echo "bucket_exists=true" >> $GITHUB_ENV
            else
              echo "Bucket does not exist."
              echo "bucket_exists=false" >> $GITHUB_ENV
            fi
  
      - name: Create GCS bucket
        if: env.bucket_exists == 'false'
        run: |
          gsutil mb -l europe-west6 gs://iaac-gcp-data-mgt-terraform

      - name: Create backend folder
        run: |
            echo "Creating backend folder in the bucket"
            gsutil cp /dev/null gs://iaac-gcp-data-mgt-terraform/backend/