name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - qa
      - main

permissions:
  id-token: write   # Required for OIDC authentication
  contents: read    # Default permission for accessing the repo

jobs:
  deploy-backend:
    name: Deploy Backend
    runs-on: ubuntu-latest
##  environment: ${{ github.ref_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set auth
        id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: "projects/571690378641/locations/global/workloadIdentityPools/github-wif-pool/subject/iaac-gcp-data-mgt"
          service_account: "github-wif-sa@iaac-gcp-data-mgt.iam.gserviceaccount.com"

      - name: List instances
        run: |
          gcloud compute instances list --project=iaac-gcp-data-mgt